import React, { useEffect, useState } from 'react';
import { listUsers, createUser, listWorkers, createWorker, resetPassword, setRole } from '../api';
export default function AdminPanel({ token }){
  const [users, setUsers] = useState([]);
  const [workers, setWorkers] = useState([]);
  const [form, setForm] = useState({ username:'', password:'', full_name:'', role:'viewer' });
  const [wform, setWform] = useState({ name:'', phone:'' });
  useEffect(()=>{ fetch(); }, []);
  async function fetch(){ try{ const u = await listUsers(token); setUsers(u.data); const w = await listWorkers(token); setWorkers(w.data);}catch(e){ console.error(e); } }
  async function submitUser(e){ e.preventDefault(); await createUser(token, form); setForm({ username:'', password:'', full_name:'', role:'viewer' }); fetch(); }
  async function submitWorker(e){ e.preventDefault(); await createWorker(token, wform); setWform({ name:'', phone:'' }); fetch(); }
  return (<div className='side-panel'><h3>Админ-панель</h3><section><h4>Пользователи</h4><form onSubmit={submitUser}><input placeholder='Логин' value={form.username} onChange={e=>setForm({...form, username:e.target.value})} /><br/><input placeholder='Пароль' value={form.password} onChange={e=>setForm({...form, password:e.target.value})} /><br/><input placeholder='ФИО' value={form.full_name} onChange={e=>setForm({...form, full_name:e.target.value})} /><br/><select value={form.role} onChange={e=>setForm({...form, role:e.target.value})}><option value='admin'>admin</option><option value='manager'>manager</option><option value='worker'>worker</option><option value='viewer'>viewer</option></select><br/><button className='btn' type='submit'>Создать</button></form><div style={{marginTop:12}}><h5>Существующие</h5>{users.map(u=> <div key={u.id} style={{padding:6,borderBottom:'1px solid #eee'}}>{u.username} — {u.full_name} — {u.role} <button className='btn secondary' onClick={async()=>{ const pw = prompt('Новый пароль'); if(pw){ await resetPassword(token, u.id, pw); alert('Сброшен'); } }}>Сброс пароля</button> <button className='btn secondary' onClick={async()=>{ const r = prompt('Новая роль (admin/manager/worker/viewer)'); if(r){ await setRole(token, u.id, r); fetch(); } }}>Изменить роль</button></div>)}</div></section><section style={{marginTop:16}}><h4>Монтажники</h4><form onSubmit={submitWorker}><input placeholder='ФИО' value={wform.name} onChange={e=>setWform({...wform, name:e.target.value})} /><br/><input placeholder='Телефон' value={wform.phone} onChange={e=>setWform({...wform, phone:e.target.value})} /><br/><button className='btn' type='submit'>Добавить монтажника</button></form><div style={{marginTop:12}}>{workers.map(w=> <div key={w.id} className='worker-item'>{w.name} {w.active? '': '(уволен)'} </div>)}</div></section></div>);
}
